start genere_ajouter_employe.bat
start genere_confirmation.bat
start genere_creer_contrat.bat
start genere_creer_specialite.bat
start genere_menu_contrat.bat
start genere_menu_employe.bat
start genere_menu_paye.bat
start genere_menu_principal.bat
start genere_menu_specialite.bat
start genere_modifier_employe.bat
exit