# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tout\Prog\Projet_intra_Entreprise\UI\Confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogConfirmation(object):
    def setupUi(self, DialogConfirmation):
        DialogConfirmation.setObjectName("DialogConfirmation")
        DialogConfirmation.resize(251, 107)
        self.labelConfirmation = QtWidgets.QLabel(DialogConfirmation)
        self.labelConfirmation.setGeometry(QtCore.QRect(10, 10, 241, 41))
        self.labelConfirmation.setAlignment(QtCore.Qt.AlignCenter)
        self.labelConfirmation.setObjectName("labelConfirmation")
        self.horizontalLayoutWidget = QtWidgets.QWidget(DialogConfirmation)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 161, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOui = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonOui.setObjectName("pushButtonOui")
        self.horizontalLayout.addWidget(self.pushButtonOui)
        self.pushButtonNon = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonNon.setObjectName("pushButtonNon")
        self.horizontalLayout.addWidget(self.pushButtonNon)

        self.retranslateUi(DialogConfirmation)
        QtCore.QMetaObject.connectSlotsByName(DialogConfirmation)

    def retranslateUi(self, DialogConfirmation):
        _translate = QtCore.QCoreApplication.translate
        DialogConfirmation.setWindowTitle(_translate("DialogConfirmation", "Dialog"))
        self.labelConfirmation.setText(_translate("DialogConfirmation", "Confirmation"))
        self.pushButtonOui.setText(_translate("DialogConfirmation", "Oui"))
        self.pushButtonNon.setText(_translate("DialogConfirmation", "Non"))
