# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tout\Prog\Projet_intra_Entreprise\UI\Creer_Specialite.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCreerSpecialite(object):
    def setupUi(self, DialogCreerSpecialite):
        DialogCreerSpecialite.setObjectName("DialogCreerSpecialite")
        DialogCreerSpecialite.resize(400, 255)
        self.pushButtonCreerSpecialote = QtWidgets.QPushButton(DialogCreerSpecialite)
        self.pushButtonCreerSpecialote.setGeometry(QtCore.QRect(20, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonCreerSpecialote.setFont(font)
        self.pushButtonCreerSpecialote.setObjectName("pushButtonCreerSpecialote")
        self.labelNom = QtWidgets.QLabel(DialogCreerSpecialite)
        self.labelNom.setGeometry(QtCore.QRect(20, 60, 40, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNom.setFont(font)
        self.labelNom.setObjectName("labelNom")
        self.labelTitreAjouterSpecialite = QtWidgets.QLabel(DialogCreerSpecialite)
        self.labelTitreAjouterSpecialite.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelTitreAjouterSpecialite.setFont(font)
        self.labelTitreAjouterSpecialite.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTitreAjouterSpecialite.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitreAjouterSpecialite.setObjectName("labelTitreAjouterSpecialite")
        self.line = QtWidgets.QFrame(DialogCreerSpecialite)
        self.line.setGeometry(QtCore.QRect(20, 40, 351, 21))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.pushButtonAnnuler = QtWidgets.QPushButton(DialogCreerSpecialite)
        self.pushButtonAnnuler.setGeometry(QtCore.QRect(220, 200, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonAnnuler.setFont(font)
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.lineEditNom = QtWidgets.QLineEdit(DialogCreerSpecialite)
        self.lineEditNom.setGeometry(QtCore.QRect(60, 68, 113, 20))
        self.lineEditNom.setObjectName("lineEditNom")
        self.labelErreurNom = QtWidgets.QLabel(DialogCreerSpecialite)
        self.labelErreurNom.setGeometry(QtCore.QRect(190, 70, 121, 16))
        self.labelErreurNom.setText("")
        self.labelErreurNom.setObjectName("labelErreurNom")
        self.labelDescription = QtWidgets.QLabel(DialogCreerSpecialite)
        self.labelDescription.setGeometry(QtCore.QRect(20, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDescription.setFont(font)
        self.labelDescription.setObjectName("labelDescription")
        self.textEditDescription = QtWidgets.QTextEdit(DialogCreerSpecialite)
        self.textEditDescription.setGeometry(QtCore.QRect(20, 120, 351, 71))
        self.textEditDescription.setObjectName("textEditDescription")

        self.retranslateUi(DialogCreerSpecialite)
        QtCore.QMetaObject.connectSlotsByName(DialogCreerSpecialite)

    def retranslateUi(self, DialogCreerSpecialite):
        _translate = QtCore.QCoreApplication.translate
        DialogCreerSpecialite.setWindowTitle(_translate("DialogCreerSpecialite", "Dialog"))
        self.pushButtonCreerSpecialote.setText(_translate("DialogCreerSpecialite", "Créer Spécialité"))
        self.labelNom.setText(_translate("DialogCreerSpecialite", "Nom:"))
        self.labelTitreAjouterSpecialite.setText(_translate("DialogCreerSpecialite", "Ajouter une spécialité"))
        self.pushButtonAnnuler.setText(_translate("DialogCreerSpecialite", "Annuler"))
        self.labelDescription.setText(_translate("DialogCreerSpecialite", "Description:"))
