# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tout\Prog\Projet_intra_Entreprise\UI\MenuContratEmploye.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogContratEmploye(object):
    def setupUi(self, DialogContratEmploye):
        DialogContratEmploye.setObjectName("DialogContratEmploye")
        DialogContratEmploye.resize(577, 429)
        self.labelContrat = QtWidgets.QLabel(DialogContratEmploye)
        self.labelContrat.setGeometry(QtCore.QRect(20, 20, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelContrat.setFont(font)
        self.labelContrat.setObjectName("labelContrat")
        self.listViewContrat = QtWidgets.QListView(DialogContratEmploye)
        self.listViewContrat.setGeometry(QtCore.QRect(20, 71, 321, 281))
        self.listViewContrat.setObjectName("listViewContrat")
        self.verticalLayoutWidget = QtWidgets.QWidget(DialogContratEmploye)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 140, 201, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonAfficherContratSelonDate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonAfficherContratSelonDate.setObjectName("pushButtonAfficherContratSelonDate")
        self.verticalLayout.addWidget(self.pushButtonAfficherContratSelonDate)
        self.dateEditContratSelonDate = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEditContratSelonDate.setObjectName("dateEditContratSelonDate")
        self.verticalLayout.addWidget(self.dateEditContratSelonDate)
        self.labelErreurAfficherContratSelonDate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelErreurAfficherContratSelonDate.setText("")
        self.labelErreurAfficherContratSelonDate.setObjectName("labelErreurAfficherContratSelonDate")
        self.verticalLayout.addWidget(self.labelErreurAfficherContratSelonDate)
        self.pushButtonReinitialiserDate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonReinitialiserDate.setObjectName("pushButtonReinitialiserDate")
        self.verticalLayout.addWidget(self.pushButtonReinitialiserDate)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(DialogContratEmploye)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(350, 70, 201, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonAfficherContratSelonEmploye = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButtonAfficherContratSelonEmploye.setObjectName("pushButtonAfficherContratSelonEmploye")
        self.verticalLayout_2.addWidget(self.pushButtonAfficherContratSelonEmploye)
        self.lineEditAfficherContratSelonEmploye = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditAfficherContratSelonEmploye.setObjectName("lineEditAfficherContratSelonEmploye")
        self.verticalLayout_2.addWidget(self.lineEditAfficherContratSelonEmploye)
        self.labelErreurSelection = QtWidgets.QLabel(DialogContratEmploye)
        self.labelErreurSelection.setGeometry(QtCore.QRect(20, 370, 531, 31))
        self.labelErreurSelection.setText("")
        self.labelErreurSelection.setObjectName("labelErreurSelection")
        self.pushButtonModifierContrat = QtWidgets.QPushButton(DialogContratEmploye)
        self.pushButtonModifierContrat.setGeometry(QtCore.QRect(350, 270, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonModifierContrat.setFont(font)
        self.pushButtonModifierContrat.setObjectName("pushButtonModifierContrat")
        self.pushButtonRetournerMenu = QtWidgets.QPushButton(DialogContratEmploye)
        self.pushButtonRetournerMenu.setGeometry(QtCore.QRect(350, 320, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonRetournerMenu.setFont(font)
        self.pushButtonRetournerMenu.setObjectName("pushButtonRetournerMenu")

        self.retranslateUi(DialogContratEmploye)
        QtCore.QMetaObject.connectSlotsByName(DialogContratEmploye)

    def retranslateUi(self, DialogContratEmploye):
        _translate = QtCore.QCoreApplication.translate
        DialogContratEmploye.setWindowTitle(_translate("DialogContratEmploye", "Dialog"))
        self.labelContrat.setText(_translate("DialogContratEmploye", "Gestionnaire des contrats"))
        self.pushButtonAfficherContratSelonDate.setText(_translate("DialogContratEmploye", "Afficher les contrats d\'une date"))
        self.pushButtonReinitialiserDate.setText(_translate("DialogContratEmploye", "Réinitialiser"))
        self.pushButtonAfficherContratSelonEmploye.setText(_translate("DialogContratEmploye", "Afficher les contrat d\'un employé"))
        self.pushButtonModifierContrat.setText(_translate("DialogContratEmploye", "Modifier"))
        self.pushButtonRetournerMenu.setText(_translate("DialogContratEmploye", "Menu"))
