# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tout\Prog\Projet_intra_Entreprise\UI\MenuPaye.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMenuPaye(object):
    def setupUi(self, DialogMenuPaye):
        DialogMenuPaye.setObjectName("DialogMenuPaye")
        DialogMenuPaye.resize(888, 695)
        self.labelErreurSelection = QtWidgets.QLabel(DialogMenuPaye)
        self.labelErreurSelection.setGeometry(QtCore.QRect(10, 409, 461, 51))
        self.labelErreurSelection.setText("")
        self.labelErreurSelection.setObjectName("labelErreurSelection")
        self.labelPaye = QtWidgets.QLabel(DialogMenuPaye)
        self.labelPaye.setGeometry(QtCore.QRect(20, 79, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelPaye.setFont(font)
        self.labelPaye.setObjectName("labelPaye")
        self.gridLayoutWidget = QtWidgets.QWidget(DialogMenuPaye)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 229, 243, 89))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.listViewListPaye = QtWidgets.QListView(DialogMenuPaye)
        self.listViewListPaye.setGeometry(QtCore.QRect(20, 130, 256, 261))
        self.listViewListPaye.setObjectName("listViewListPaye")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(DialogMenuPaye)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 110, 201, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelRechercherEmployePaye = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelRechercherEmployePaye.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRechercherEmployePaye.setObjectName("labelRechercherEmployePaye")
        self.verticalLayout_2.addWidget(self.labelRechercherEmployePaye)
        self.lineEditRechercherEmployer = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditRechercherEmployer.setObjectName("lineEditRechercherEmployer")
        self.verticalLayout_2.addWidget(self.lineEditRechercherEmployer)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(DialogMenuPaye)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(500, 110, 201, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelRechercherEmployeDate = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelRechercherEmployeDate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRechercherEmployeDate.setObjectName("labelRechercherEmployeDate")
        self.verticalLayout_3.addWidget(self.labelRechercherEmployeDate)
        self.dateEditRechercherPaye = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateEditRechercherPaye.setObjectName("dateEditRechercherPaye")
        self.verticalLayout_3.addWidget(self.dateEditRechercherPaye)
        self.pushButtonRetournerMenu = QtWidgets.QPushButton(DialogMenuPaye)
        self.pushButtonRetournerMenu.setGeometry(QtCore.QRect(290, 330, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonRetournerMenu.setFont(font)
        self.pushButtonRetournerMenu.setObjectName("pushButtonRetournerMenu")

        self.retranslateUi(DialogMenuPaye)
        QtCore.QMetaObject.connectSlotsByName(DialogMenuPaye)

    def retranslateUi(self, DialogMenuPaye):
        _translate = QtCore.QCoreApplication.translate
        DialogMenuPaye.setWindowTitle(_translate("DialogMenuPaye", "Dialog"))
        self.labelPaye.setText(_translate("DialogMenuPaye", "Paye"))
        self.checkBox_2.setText(_translate("DialogMenuPaye", "Medianne"))
        self.checkBox.setText(_translate("DialogMenuPaye", "Maximum"))
        self.checkBox_3.setText(_translate("DialogMenuPaye", "Minimum"))
        self.checkBox_5.setText(_translate("DialogMenuPaye", "Moyenne"))
        self.labelRechercherEmployePaye.setText(_translate("DialogMenuPaye", "Rechercher un employé"))
        self.labelRechercherEmployeDate.setText(_translate("DialogMenuPaye", "Rechercher une date"))
        self.pushButtonRetournerMenu.setText(_translate("DialogMenuPaye", "Menu"))
