# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tout\Prog\Projet_intra_Entreprise\UI\MenuPaye.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMenuPaye(object):
    def setupUi(self, DialogMenuPaye):
        DialogMenuPaye.setObjectName("DialogMenuPaye")
        DialogMenuPaye.resize(473, 366)
        self.labelErreurPaye = QtWidgets.QLabel(DialogMenuPaye)
        self.labelErreurPaye.setGeometry(QtCore.QRect(20, 320, 431, 21))
        self.labelErreurPaye.setText("")
        self.labelErreurPaye.setObjectName("labelErreurPaye")
        self.labelPaye = QtWidgets.QLabel(DialogMenuPaye)
        self.labelPaye.setGeometry(QtCore.QRect(20, 9, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelPaye.setFont(font)
        self.labelPaye.setObjectName("labelPaye")
        self.gridLayoutWidget = QtWidgets.QWidget(DialogMenuPaye)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 168, 161, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxMedianne = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxMedianne.setObjectName("checkBoxMedianne")
        self.gridLayout.addWidget(self.checkBoxMedianne, 1, 1, 1, 1)
        self.checkBoxMax = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxMax.setObjectName("checkBoxMax")
        self.gridLayout.addWidget(self.checkBoxMax, 0, 0, 1, 1)
        self.checkBoxMin = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxMin.setObjectName("checkBoxMin")
        self.gridLayout.addWidget(self.checkBoxMin, 1, 0, 1, 1)
        self.checkBoxMoyenne = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxMoyenne.setObjectName("checkBoxMoyenne")
        self.gridLayout.addWidget(self.checkBoxMoyenne, 0, 1, 1, 1)
        self.listViewPaye = QtWidgets.QListView(DialogMenuPaye)
        self.listViewPaye.setGeometry(QtCore.QRect(20, 50, 256, 261))
        self.listViewPaye.setObjectName("listViewPaye")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(DialogMenuPaye)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 50, 161, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelRechercherEmployePaye = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelRechercherEmployePaye.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRechercherEmployePaye.setObjectName("labelRechercherEmployePaye")
        self.verticalLayout_2.addWidget(self.labelRechercherEmployePaye)
        self.lineEditRechercherEmploye = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditRechercherEmploye.setObjectName("lineEditRechercherEmploye")
        self.verticalLayout_2.addWidget(self.lineEditRechercherEmploye)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(DialogMenuPaye)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(290, 110, 161, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelRechercherEmployeDate = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelRechercherEmployeDate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRechercherEmployeDate.setObjectName("labelRechercherEmployeDate")
        self.verticalLayout_3.addWidget(self.labelRechercherEmployeDate)
        self.dateEditRechercherPaye = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateEditRechercherPaye.setObjectName("dateEditRechercherPaye")
        self.verticalLayout_3.addWidget(self.dateEditRechercherPaye)
        self.pushButtonRetournerMenu = QtWidgets.QPushButton(DialogMenuPaye)
        self.pushButtonRetournerMenu.setGeometry(QtCore.QRect(290, 250, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButtonRetournerMenu.setFont(font)
        self.pushButtonRetournerMenu.setObjectName("pushButtonRetournerMenu")

        self.retranslateUi(DialogMenuPaye)
        QtCore.QMetaObject.connectSlotsByName(DialogMenuPaye)

    def retranslateUi(self, DialogMenuPaye):
        _translate = QtCore.QCoreApplication.translate
        DialogMenuPaye.setWindowTitle(_translate("DialogMenuPaye", "Dialog"))
        self.labelPaye.setText(_translate("DialogMenuPaye", "Gestionnaire des payes"))
        self.checkBoxMedianne.setText(_translate("DialogMenuPaye", "Medianne"))
        self.checkBoxMax.setText(_translate("DialogMenuPaye", "Maximum"))
        self.checkBoxMin.setText(_translate("DialogMenuPaye", "Minimum"))
        self.checkBoxMoyenne.setText(_translate("DialogMenuPaye", "Moyenne"))
        self.labelRechercherEmployePaye.setText(_translate("DialogMenuPaye", "Rechercher un employé"))
        self.labelRechercherEmployeDate.setText(_translate("DialogMenuPaye", "Rechercher une date"))
        self.pushButtonRetournerMenu.setText(_translate("DialogMenuPaye", "Menu"))
